name: Download, Compress, and Upload

on:
  workflow_dispatch:
    inputs:
      file_url:
        description: 'URL of the file to download'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download file
      run: |
        mkdir sources
        wget ${{ inputs.file_url }} -O input_file.txt | tee -a logs.txt
        echo "downloaded inputfile" >> logs.txt
        wget --input-file=input_file.txt --continue --directory-prefix=sources/ | tee -a logs.txt

    - name: Compress file
      run: |
        zip -r sources.zip sources

    - name: Upload zip to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: sources.zip
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true

    
    - name: Upload log to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: logs.txt
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true

