name: Download, Compress, and Upload

on:
  workflow_dispatch:
    inputs:
      file_url:
        description: 'URL of the file to download'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download file
      run: |
        mkdir sources
        wget ${{ inputs.file_url }} -O input_file.txt
        echo "downloaded inputfile"
        wget --input-file=input_file.txt --continue --directory-prefix=sources/
        
    - name: Compress file
      run: |
        echo 'compression logs' >> logs.txt
        zip -r sources.zip sources 

    - name: Create Release
      id: create-new-release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false

    - name: Upload zip to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: sources.zip
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
