on:
  workflow_dispatch:
    inputs:
      file_url:
        description: 'URL of the file to download'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download file
      run: |
        mkdir sources
        wget ${{ inputs.file_url }} -O input_file.txt
        wget --input-file=input_file.txt --continue --directory-prefix=sources/
        
    - name: Compress file
      run: |
        cd sources
        tar -cvf ../sources.tar.gz *
        cd ..

    - name: Upload release asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./sources.tar.gz
        asset_name: sources.tar.gz
        asset_content_type: application/x-bzip2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
